export const cities = [
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'San Francisco',
  'Fort Worth',
  'Charlotte',
  'Seattle',
  'Denver',
  'Washington',
  'Boston',
  'El Paso',
  'Detroit',
  'Nashville',
  'Portland',
  'Memphis',
  'Oklahoma City',
  'Las Vegas',
  'Louisville',
  'Baltimore',
  'Milwaukee',
  'Albuquerque',
  'Tucson',
  'Fresno',
  'Sacramento',
  'Kansas City',
  'Long Beach',
  'Mesa',
  'Atlanta',
  'Colorado Springs',
  'Virginia Beach',
  'Raleigh',
  'Omaha',
  'Miami',
  'Oakland',
  'Minneapolis',
  'Tulsa',
  'Wichita',
  'New Orleans',
  'Arlington',
  'Cleveland',
  'Bakersfield',
  'Tampa',
  'Aurora',
  'Honolulu',
  'Anaheim',
  'Santa Ana',
  'Corpus Christi',
  'Riverside',
  'St. Louis',
  'Lexington',
  'Pittsburgh',
  'Stockton',
  'Anchorage',
  'Cincinnati',
  'St. Paul',
  'Greensboro',
  'Toledo',
  'Newark',
  'Plano',
  'Henderson',
  'Lincoln',
  'Orlando',
  'Jersey City',
  'Chula Vista',
  'Buffalo',
  'Fort Wayne',
  'Chandler',
  'St. Petersburg',
  'Laredo',
  'Durham',
  'Irvine',
  'Madison',
  'Norfolk',
  'Lubbock',
  'Gilbert',
  'Winston-Salem',
  'Glendale',
  'Reno',
  'Hialeah',
  'Garland',
  'Chesapeake',
  'Irving',
  'North Las Vegas',
  'Scottsdale',
  'Baton Rouge',
  'Fremont',
  'Richmond',
  'Boise',
  'San Bernardino'
];
